name: Build
on: [push, pull_request]

env:
  SDK_VERSION: 2.1.1

jobs:
  build:
    name: PicoFlasher Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board: [pico, pico2]

    steps:
      - name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
        uses: carlosperate/arm-none-eabi-gcc-action@v1

      - name: Checkout pico-sdk
        uses: actions/checkout@v4
        with:
          repository: raspberrypi/pico-sdk
          ref: ${{ env.SDK_VERSION }}
          path: pico-sdk
          submodules: true

      - name: Checkout picotool
        uses: actions/checkout@v4
        with:
          repository: raspberrypi/picotool
          ref: ${{ env.SDK_VERSION }}
          path: picotool

      - name: Build and Install picotool
        env:
          PICO_SDK_PATH: ${{ github.workspace }}/pico-sdk
        run: |
          cmake -S picotool -B picotool/build -G "Ninja"
          cmake --build picotool/build
          sudo cmake --install picotool/build

      - name: Checkout PicoFlasher
        uses: actions/checkout@v4
        with:
          path: picoflasher

      - name: Build PicoFlasher
        env:
          PICO_SDK_PATH: ${{ github.workspace }}/pico-sdk
          PICO_BOARD: ${{ matrix.board }}
        run: |
          cmake -S picoflasher -B picoflasher/build -DCMAKE_BUILD_TYPE=Release
          cmake --build picoflasher/build --config Release --parallel $(nproc)

      - name: Upload PicoFlasher
        uses: actions/upload-artifact@v4
        with:
          name: picoflasher-${{ matrix.board }}
          path: picoflasher/build/PicoFlasher.uf2
